language: generic
sudo: required
services:
  - docker

before_install:
  - docker build --tag smcook55/docker-react --file Dockerfile.dev .

script:
  - docker run --env CI=true smcook55/docker-react npm run test